version: "3"
services:
  app:
    build:
      context: ./
      labels:
        - app=tvshows
      dockerfile: Dockerfile
    image: tvshows
    ports:
      - "3000:80"
    restart: always
    mem_limit: 1G

